spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/wangdb
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
          # 基础配置省略...
          init:
            schema: db/master/schema.sql # 配置则生效,自动初始化表结构
            data: db/master/data.sql # 配置则生效,自动初始化数据
            continue-on-error: true # 默认true,初始化失败是否继续
            separator: ";" # sql默认分号分隔符，一般无需更改
        slave_1:
          url: jdbc:mysql://localhost:3306/test
          username: root
          password: root
        slave_2:
          url: jdbc:mysql://localhost:3306/test_orders
          username: root
          password: root
#        slave_2:
#          url: ENC(xxxxx) # 内置加密,使用请查看详细文档
#          username: ENC(xxxxx)
#          password: ENC(xxxxx)
#          driver-class-name: com.mysql.jdbc.Driver
        #......省略
        #以上会配置一个默认库master，一个组slave下有两个子库slave_1,slave_2