spring:
  redis:
    host: localhost
    port: 6379
    connect-timeout: 5000
    timeout: 5000

    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms