spring:
  redis:
    host: localhost
    port: 6379
#    username:
#    password:
    database: 0
    # 读超时
    timeout: 3s
    # 连接超时
    connect-timeout: 3s

    # Lettuce 客户端的配置
    lettuce:
      # 连接池配置
      pool:
        # 最小空闲连接
        min-idle: 4
        # 最大空闲连接
        max-idle: 16
        # 最大活跃连接
        max-active: 32
        # 从连接池获取连接 最大超时时间
        max-wait: 3000ms